# Generated by Django 4.2.5 on 2023-12-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_data',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee_data',
            name='emp_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
